services:
  bot-app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.bot
    image: link-tracker-bot:latest
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped

  scrapper-app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.scrapper
    image: link-tracker-scrapper:latest
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped

  agent-app:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.agent
    image: link-tracker-agent:latest
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped
