// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/scrapper/infrastructure/db/orm/model"
)

func newFilter(db *gorm.DB, opts ...gen.DOOption) filter {
	_filter := filter{}

	_filter.filterDo.UseDB(db, opts...)
	_filter.filterDo.UseModel(&model.Filter{})

	tableName := _filter.filterDo.TableName()
	_filter.ALL = field.NewAsterisk(tableName)
	_filter.ID = field.NewInt64(tableName, "id")
	_filter.Value = field.NewString(tableName, "value")

	_filter.fillFieldMap()

	return _filter
}

type filter struct {
	filterDo

	ALL   field.Asterisk
	ID    field.Int64
	Value field.String

	fieldMap map[string]field.Expr
}

func (f filter) Table(newTableName string) *filter {
	f.filterDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f filter) As(alias string) *filter {
	f.filterDo.DO = *(f.filterDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *filter) updateTableName(table string) *filter {
	f.ALL = field.NewAsterisk(table)
	f.ID = field.NewInt64(table, "id")
	f.Value = field.NewString(table, "value")

	f.fillFieldMap()

	return f
}

func (f *filter) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *filter) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 2)
	f.fieldMap["id"] = f.ID
	f.fieldMap["value"] = f.Value
}

func (f filter) clone(db *gorm.DB) filter {
	f.filterDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f filter) replaceDB(db *gorm.DB) filter {
	f.filterDo.ReplaceDB(db)
	return f
}

type filterDo struct{ gen.DO }

func (f filterDo) Debug() *filterDo {
	return f.withDO(f.DO.Debug())
}

func (f filterDo) WithContext(ctx context.Context) *filterDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f filterDo) ReadDB() *filterDo {
	return f.Clauses(dbresolver.Read)
}

func (f filterDo) WriteDB() *filterDo {
	return f.Clauses(dbresolver.Write)
}

func (f filterDo) Session(config *gorm.Session) *filterDo {
	return f.withDO(f.DO.Session(config))
}

func (f filterDo) Clauses(conds ...clause.Expression) *filterDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f filterDo) Returning(value interface{}, columns ...string) *filterDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f filterDo) Not(conds ...gen.Condition) *filterDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f filterDo) Or(conds ...gen.Condition) *filterDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f filterDo) Select(conds ...field.Expr) *filterDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f filterDo) Where(conds ...gen.Condition) *filterDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f filterDo) Order(conds ...field.Expr) *filterDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f filterDo) Distinct(cols ...field.Expr) *filterDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f filterDo) Omit(cols ...field.Expr) *filterDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f filterDo) Join(table schema.Tabler, on ...field.Expr) *filterDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f filterDo) LeftJoin(table schema.Tabler, on ...field.Expr) *filterDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f filterDo) RightJoin(table schema.Tabler, on ...field.Expr) *filterDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f filterDo) Group(cols ...field.Expr) *filterDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f filterDo) Having(conds ...gen.Condition) *filterDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f filterDo) Limit(limit int) *filterDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f filterDo) Offset(offset int) *filterDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f filterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *filterDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f filterDo) Unscoped() *filterDo {
	return f.withDO(f.DO.Unscoped())
}

func (f filterDo) Create(values ...*model.Filter) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f filterDo) CreateInBatches(values []*model.Filter, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f filterDo) Save(values ...*model.Filter) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f filterDo) First() (*model.Filter, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Filter), nil
	}
}

func (f filterDo) Take() (*model.Filter, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Filter), nil
	}
}

func (f filterDo) Last() (*model.Filter, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Filter), nil
	}
}

func (f filterDo) Find() ([]*model.Filter, error) {
	result, err := f.DO.Find()
	return result.([]*model.Filter), err
}

func (f filterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Filter, err error) {
	buf := make([]*model.Filter, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f filterDo) FindInBatches(result *[]*model.Filter, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f filterDo) Attrs(attrs ...field.AssignExpr) *filterDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f filterDo) Assign(attrs ...field.AssignExpr) *filterDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f filterDo) Joins(fields ...field.RelationField) *filterDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f filterDo) Preload(fields ...field.RelationField) *filterDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f filterDo) FirstOrInit() (*model.Filter, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Filter), nil
	}
}

func (f filterDo) FirstOrCreate() (*model.Filter, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Filter), nil
	}
}

func (f filterDo) FindByPage(offset int, limit int) (result []*model.Filter, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f filterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f filterDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f filterDo) Delete(models ...*model.Filter) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *filterDo) withDO(do gen.Dao) *filterDo {
	f.DO = *do.(*gen.DO)
	return f
}
