// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:           db,
		Chat:         newChat(db, opts...),
		Filter:       newFilter(db, opts...),
		Link:         newLink(db, opts...),
		LinkFilter:   newLinkFilter(db, opts...),
		LinkTag:      newLinkTag(db, opts...),
		Subscription: newSubscription(db, opts...),
		Tag:          newTag(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Chat         chat
	Filter       filter
	Link         link
	LinkFilter   linkFilter
	LinkTag      linkTag
	Subscription subscription
	Tag          tag
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Chat:         q.Chat.clone(db),
		Filter:       q.Filter.clone(db),
		Link:         q.Link.clone(db),
		LinkFilter:   q.LinkFilter.clone(db),
		LinkTag:      q.LinkTag.clone(db),
		Subscription: q.Subscription.clone(db),
		Tag:          q.Tag.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:           db,
		Chat:         q.Chat.replaceDB(db),
		Filter:       q.Filter.replaceDB(db),
		Link:         q.Link.replaceDB(db),
		LinkFilter:   q.LinkFilter.replaceDB(db),
		LinkTag:      q.LinkTag.replaceDB(db),
		Subscription: q.Subscription.replaceDB(db),
		Tag:          q.Tag.replaceDB(db),
	}
}

type queryCtx struct {
	Chat         *chatDo
	Filter       *filterDo
	Link         *linkDo
	LinkFilter   *linkFilterDo
	LinkTag      *linkTagDo
	Subscription *subscriptionDo
	Tag          *tagDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Chat:         q.Chat.WithContext(ctx),
		Filter:       q.Filter.WithContext(ctx),
		Link:         q.Link.WithContext(ctx),
		LinkFilter:   q.LinkFilter.WithContext(ctx),
		LinkTag:      q.LinkTag.WithContext(ctx),
		Subscription: q.Subscription.WithContext(ctx),
		Tag:          q.Tag.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
