// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/scrapper/infrastructure/db/orm/model"
)

func newLinkFilter(db *gorm.DB, opts ...gen.DOOption) linkFilter {
	_linkFilter := linkFilter{}

	_linkFilter.linkFilterDo.UseDB(db, opts...)
	_linkFilter.linkFilterDo.UseModel(&model.LinkFilter{})

	tableName := _linkFilter.linkFilterDo.TableName()
	_linkFilter.ALL = field.NewAsterisk(tableName)
	_linkFilter.SubscriptionID = field.NewInt64(tableName, "subscription_id")
	_linkFilter.FilterID = field.NewInt64(tableName, "filter_id")

	_linkFilter.fillFieldMap()

	return _linkFilter
}

type linkFilter struct {
	linkFilterDo

	ALL            field.Asterisk
	SubscriptionID field.Int64
	FilterID       field.Int64

	fieldMap map[string]field.Expr
}

func (l linkFilter) Table(newTableName string) *linkFilter {
	l.linkFilterDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l linkFilter) As(alias string) *linkFilter {
	l.linkFilterDo.DO = *(l.linkFilterDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *linkFilter) updateTableName(table string) *linkFilter {
	l.ALL = field.NewAsterisk(table)
	l.SubscriptionID = field.NewInt64(table, "subscription_id")
	l.FilterID = field.NewInt64(table, "filter_id")

	l.fillFieldMap()

	return l
}

func (l *linkFilter) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *linkFilter) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 2)
	l.fieldMap["subscription_id"] = l.SubscriptionID
	l.fieldMap["filter_id"] = l.FilterID
}

func (l linkFilter) clone(db *gorm.DB) linkFilter {
	l.linkFilterDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l linkFilter) replaceDB(db *gorm.DB) linkFilter {
	l.linkFilterDo.ReplaceDB(db)
	return l
}

type linkFilterDo struct{ gen.DO }

func (l linkFilterDo) Debug() *linkFilterDo {
	return l.withDO(l.DO.Debug())
}

func (l linkFilterDo) WithContext(ctx context.Context) *linkFilterDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l linkFilterDo) ReadDB() *linkFilterDo {
	return l.Clauses(dbresolver.Read)
}

func (l linkFilterDo) WriteDB() *linkFilterDo {
	return l.Clauses(dbresolver.Write)
}

func (l linkFilterDo) Session(config *gorm.Session) *linkFilterDo {
	return l.withDO(l.DO.Session(config))
}

func (l linkFilterDo) Clauses(conds ...clause.Expression) *linkFilterDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l linkFilterDo) Returning(value interface{}, columns ...string) *linkFilterDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l linkFilterDo) Not(conds ...gen.Condition) *linkFilterDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l linkFilterDo) Or(conds ...gen.Condition) *linkFilterDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l linkFilterDo) Select(conds ...field.Expr) *linkFilterDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l linkFilterDo) Where(conds ...gen.Condition) *linkFilterDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l linkFilterDo) Order(conds ...field.Expr) *linkFilterDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l linkFilterDo) Distinct(cols ...field.Expr) *linkFilterDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l linkFilterDo) Omit(cols ...field.Expr) *linkFilterDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l linkFilterDo) Join(table schema.Tabler, on ...field.Expr) *linkFilterDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l linkFilterDo) LeftJoin(table schema.Tabler, on ...field.Expr) *linkFilterDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l linkFilterDo) RightJoin(table schema.Tabler, on ...field.Expr) *linkFilterDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l linkFilterDo) Group(cols ...field.Expr) *linkFilterDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l linkFilterDo) Having(conds ...gen.Condition) *linkFilterDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l linkFilterDo) Limit(limit int) *linkFilterDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l linkFilterDo) Offset(offset int) *linkFilterDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l linkFilterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *linkFilterDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l linkFilterDo) Unscoped() *linkFilterDo {
	return l.withDO(l.DO.Unscoped())
}

func (l linkFilterDo) Create(values ...*model.LinkFilter) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l linkFilterDo) CreateInBatches(values []*model.LinkFilter, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l linkFilterDo) Save(values ...*model.LinkFilter) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l linkFilterDo) First() (*model.LinkFilter, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkFilter), nil
	}
}

func (l linkFilterDo) Take() (*model.LinkFilter, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkFilter), nil
	}
}

func (l linkFilterDo) Last() (*model.LinkFilter, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkFilter), nil
	}
}

func (l linkFilterDo) Find() ([]*model.LinkFilter, error) {
	result, err := l.DO.Find()
	return result.([]*model.LinkFilter), err
}

func (l linkFilterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LinkFilter, err error) {
	buf := make([]*model.LinkFilter, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l linkFilterDo) FindInBatches(result *[]*model.LinkFilter, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l linkFilterDo) Attrs(attrs ...field.AssignExpr) *linkFilterDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l linkFilterDo) Assign(attrs ...field.AssignExpr) *linkFilterDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l linkFilterDo) Joins(fields ...field.RelationField) *linkFilterDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l linkFilterDo) Preload(fields ...field.RelationField) *linkFilterDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l linkFilterDo) FirstOrInit() (*model.LinkFilter, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkFilter), nil
	}
}

func (l linkFilterDo) FirstOrCreate() (*model.LinkFilter, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkFilter), nil
	}
}

func (l linkFilterDo) FindByPage(offset int, limit int) (result []*model.LinkFilter, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l linkFilterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l linkFilterDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l linkFilterDo) Delete(models ...*model.LinkFilter) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *linkFilterDo) withDO(do gen.Dao) *linkFilterDo {
	l.DO = *do.(*gen.DO)
	return l
}
