// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/scrapper/infrastructure/db/orm/model"
)

func newLinkTag(db *gorm.DB, opts ...gen.DOOption) linkTag {
	_linkTag := linkTag{}

	_linkTag.linkTagDo.UseDB(db, opts...)
	_linkTag.linkTagDo.UseModel(&model.LinkTag{})

	tableName := _linkTag.linkTagDo.TableName()
	_linkTag.ALL = field.NewAsterisk(tableName)
	_linkTag.SubscriptionID = field.NewInt64(tableName, "subscription_id")
	_linkTag.TagID = field.NewInt64(tableName, "tag_id")

	_linkTag.fillFieldMap()

	return _linkTag
}

type linkTag struct {
	linkTagDo

	ALL            field.Asterisk
	SubscriptionID field.Int64
	TagID          field.Int64

	fieldMap map[string]field.Expr
}

func (l linkTag) Table(newTableName string) *linkTag {
	l.linkTagDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l linkTag) As(alias string) *linkTag {
	l.linkTagDo.DO = *(l.linkTagDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *linkTag) updateTableName(table string) *linkTag {
	l.ALL = field.NewAsterisk(table)
	l.SubscriptionID = field.NewInt64(table, "subscription_id")
	l.TagID = field.NewInt64(table, "tag_id")

	l.fillFieldMap()

	return l
}

func (l *linkTag) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *linkTag) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 2)
	l.fieldMap["subscription_id"] = l.SubscriptionID
	l.fieldMap["tag_id"] = l.TagID
}

func (l linkTag) clone(db *gorm.DB) linkTag {
	l.linkTagDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l linkTag) replaceDB(db *gorm.DB) linkTag {
	l.linkTagDo.ReplaceDB(db)
	return l
}

type linkTagDo struct{ gen.DO }

func (l linkTagDo) Debug() *linkTagDo {
	return l.withDO(l.DO.Debug())
}

func (l linkTagDo) WithContext(ctx context.Context) *linkTagDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l linkTagDo) ReadDB() *linkTagDo {
	return l.Clauses(dbresolver.Read)
}

func (l linkTagDo) WriteDB() *linkTagDo {
	return l.Clauses(dbresolver.Write)
}

func (l linkTagDo) Session(config *gorm.Session) *linkTagDo {
	return l.withDO(l.DO.Session(config))
}

func (l linkTagDo) Clauses(conds ...clause.Expression) *linkTagDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l linkTagDo) Returning(value interface{}, columns ...string) *linkTagDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l linkTagDo) Not(conds ...gen.Condition) *linkTagDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l linkTagDo) Or(conds ...gen.Condition) *linkTagDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l linkTagDo) Select(conds ...field.Expr) *linkTagDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l linkTagDo) Where(conds ...gen.Condition) *linkTagDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l linkTagDo) Order(conds ...field.Expr) *linkTagDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l linkTagDo) Distinct(cols ...field.Expr) *linkTagDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l linkTagDo) Omit(cols ...field.Expr) *linkTagDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l linkTagDo) Join(table schema.Tabler, on ...field.Expr) *linkTagDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l linkTagDo) LeftJoin(table schema.Tabler, on ...field.Expr) *linkTagDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l linkTagDo) RightJoin(table schema.Tabler, on ...field.Expr) *linkTagDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l linkTagDo) Group(cols ...field.Expr) *linkTagDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l linkTagDo) Having(conds ...gen.Condition) *linkTagDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l linkTagDo) Limit(limit int) *linkTagDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l linkTagDo) Offset(offset int) *linkTagDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l linkTagDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *linkTagDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l linkTagDo) Unscoped() *linkTagDo {
	return l.withDO(l.DO.Unscoped())
}

func (l linkTagDo) Create(values ...*model.LinkTag) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l linkTagDo) CreateInBatches(values []*model.LinkTag, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l linkTagDo) Save(values ...*model.LinkTag) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l linkTagDo) First() (*model.LinkTag, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkTag), nil
	}
}

func (l linkTagDo) Take() (*model.LinkTag, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkTag), nil
	}
}

func (l linkTagDo) Last() (*model.LinkTag, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkTag), nil
	}
}

func (l linkTagDo) Find() ([]*model.LinkTag, error) {
	result, err := l.DO.Find()
	return result.([]*model.LinkTag), err
}

func (l linkTagDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LinkTag, err error) {
	buf := make([]*model.LinkTag, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l linkTagDo) FindInBatches(result *[]*model.LinkTag, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l linkTagDo) Attrs(attrs ...field.AssignExpr) *linkTagDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l linkTagDo) Assign(attrs ...field.AssignExpr) *linkTagDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l linkTagDo) Joins(fields ...field.RelationField) *linkTagDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l linkTagDo) Preload(fields ...field.RelationField) *linkTagDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l linkTagDo) FirstOrInit() (*model.LinkTag, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkTag), nil
	}
}

func (l linkTagDo) FirstOrCreate() (*model.LinkTag, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LinkTag), nil
	}
}

func (l linkTagDo) FindByPage(offset int, limit int) (result []*model.LinkTag, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l linkTagDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l linkTagDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l linkTagDo) Delete(models ...*model.LinkTag) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *linkTagDo) withDO(do gen.Dao) *linkTagDo {
	l.DO = *do.(*gen.DO)
	return l
}
