// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/scrapper/application (interfaces: ChatUseCase,LinksCache,SchedulerLinks,BotNotifier,LinkChecker)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks . ChatUseCase,LinksCache,SchedulerLinks,BotNotifier,LinkChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/scrapper/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockChatUseCase is a mock of ChatUseCase interface.
type MockChatUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockChatUseCaseMockRecorder
	isgomock struct{}
}

// MockChatUseCaseMockRecorder is the mock recorder for MockChatUseCase.
type MockChatUseCaseMockRecorder struct {
	mock *MockChatUseCase
}

// NewMockChatUseCase creates a new mock instance.
func NewMockChatUseCase(ctrl *gomock.Controller) *MockChatUseCase {
	mock := &MockChatUseCase{ctrl: ctrl}
	mock.recorder = &MockChatUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatUseCase) EXPECT() *MockChatUseCaseMockRecorder {
	return m.recorder
}

// ChatDelition mocks base method.
func (m *MockChatUseCase) ChatDelition(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatDelition", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatDelition indicates an expected call of ChatDelition.
func (mr *MockChatUseCaseMockRecorder) ChatDelition(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatDelition", reflect.TypeOf((*MockChatUseCase)(nil).ChatDelition), ctx, id)
}

// ChatRegistration mocks base method.
func (m *MockChatUseCase) ChatRegistration(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatRegistration", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChatRegistration indicates an expected call of ChatRegistration.
func (mr *MockChatUseCaseMockRecorder) ChatRegistration(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatRegistration", reflect.TypeOf((*MockChatUseCase)(nil).ChatRegistration), ctx, id)
}

// DeleteLink mocks base method.
func (m *MockChatUseCase) DeleteLink(ctx context.Context, chatID int64, linkURL string) (domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLink", ctx, chatID, linkURL)
	ret0, _ := ret[0].(domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLink indicates an expected call of DeleteLink.
func (mr *MockChatUseCaseMockRecorder) DeleteLink(ctx, chatID, linkURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLink", reflect.TypeOf((*MockChatUseCase)(nil).DeleteLink), ctx, chatID, linkURL)
}

// GetLinks mocks base method.
func (m *MockChatUseCase) GetLinks(ctx context.Context, chatID int64) ([]domain.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinks", ctx, chatID)
	ret0, _ := ret[0].([]domain.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinks indicates an expected call of GetLinks.
func (mr *MockChatUseCaseMockRecorder) GetLinks(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinks", reflect.TypeOf((*MockChatUseCase)(nil).GetLinks), ctx, chatID)
}

// LinkAddment mocks base method.
func (m *MockChatUseCase) LinkAddment(ctx context.Context, chatID int64, link string, tags, filters *[]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkAddment", ctx, chatID, link, tags, filters)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkAddment indicates an expected call of LinkAddment.
func (mr *MockChatUseCaseMockRecorder) LinkAddment(ctx, chatID, link, tags, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkAddment", reflect.TypeOf((*MockChatUseCase)(nil).LinkAddment), ctx, chatID, link, tags, filters)
}

// MockLinksCache is a mock of LinksCache interface.
type MockLinksCache struct {
	ctrl     *gomock.Controller
	recorder *MockLinksCacheMockRecorder
	isgomock struct{}
}

// MockLinksCacheMockRecorder is the mock recorder for MockLinksCache.
type MockLinksCacheMockRecorder struct {
	mock *MockLinksCache
}

// NewMockLinksCache creates a new mock instance.
func NewMockLinksCache(ctrl *gomock.Controller) *MockLinksCache {
	mock := &MockLinksCache{ctrl: ctrl}
	mock.recorder = &MockLinksCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinksCache) EXPECT() *MockLinksCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockLinksCache) Get(ctx context.Context, chatID int64) ([]domain.Link, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, chatID)
	ret0, _ := ret[0].([]domain.Link)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockLinksCacheMockRecorder) Get(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLinksCache)(nil).Get), ctx, chatID)
}

// Invalidate mocks base method.
func (m *MockLinksCache) Invalidate(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invalidate", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Invalidate indicates an expected call of Invalidate.
func (mr *MockLinksCacheMockRecorder) Invalidate(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invalidate", reflect.TypeOf((*MockLinksCache)(nil).Invalidate), ctx, chatID)
}

// Set mocks base method.
func (m *MockLinksCache) Set(ctx context.Context, chatID int64, links []domain.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, chatID, links)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockLinksCacheMockRecorder) Set(ctx, chatID, links any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockLinksCache)(nil).Set), ctx, chatID, links)
}

// MockSchedulerLinks is a mock of SchedulerLinks interface.
type MockSchedulerLinks struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerLinksMockRecorder
	isgomock struct{}
}

// MockSchedulerLinksMockRecorder is the mock recorder for MockSchedulerLinks.
type MockSchedulerLinksMockRecorder struct {
	mock *MockSchedulerLinks
}

// NewMockSchedulerLinks creates a new mock instance.
func NewMockSchedulerLinks(ctrl *gomock.Controller) *MockSchedulerLinks {
	mock := &MockSchedulerLinks{ctrl: ctrl}
	mock.recorder = &MockSchedulerLinksMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchedulerLinks) EXPECT() *MockSchedulerLinksMockRecorder {
	return m.recorder
}

// ListSubscribedLinks mocks base method.
func (m *MockSchedulerLinks) ListSubscribedLinks(ctx context.Context, limit, offset int) ([]domain.SubscribedLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscribedLinks", ctx, limit, offset)
	ret0, _ := ret[0].([]domain.SubscribedLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscribedLinks indicates an expected call of ListSubscribedLinks.
func (mr *MockSchedulerLinksMockRecorder) ListSubscribedLinks(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscribedLinks", reflect.TypeOf((*MockSchedulerLinks)(nil).ListSubscribedLinks), ctx, limit, offset)
}

// UpdateLinkUpdatedAt mocks base method.
func (m *MockSchedulerLinks) UpdateLinkUpdatedAt(ctx context.Context, chatID int64, linkURL string, t time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLinkUpdatedAt", ctx, chatID, linkURL, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLinkUpdatedAt indicates an expected call of UpdateLinkUpdatedAt.
func (mr *MockSchedulerLinksMockRecorder) UpdateLinkUpdatedAt(ctx, chatID, linkURL, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLinkUpdatedAt", reflect.TypeOf((*MockSchedulerLinks)(nil).UpdateLinkUpdatedAt), ctx, chatID, linkURL, t)
}

// MockBotNotifier is a mock of BotNotifier interface.
type MockBotNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockBotNotifierMockRecorder
	isgomock struct{}
}

// MockBotNotifierMockRecorder is the mock recorder for MockBotNotifier.
type MockBotNotifierMockRecorder struct {
	mock *MockBotNotifier
}

// NewMockBotNotifier creates a new mock instance.
func NewMockBotNotifier(ctrl *gomock.Controller) *MockBotNotifier {
	mock := &MockBotNotifier{ctrl: ctrl}
	mock.recorder = &MockBotNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBotNotifier) EXPECT() *MockBotNotifierMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockBotNotifier) Notify(ctx context.Context, chatID int64, link domain.Link, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, chatID, link, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockBotNotifierMockRecorder) Notify(ctx, chatID, link, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockBotNotifier)(nil).Notify), ctx, chatID, link, description)
}

// NotifyFailedLinks mocks base method.
func (m *MockBotNotifier) NotifyFailedLinks(ctx context.Context, chatID int64, links []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyFailedLinks", ctx, chatID, links)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyFailedLinks indicates an expected call of NotifyFailedLinks.
func (mr *MockBotNotifierMockRecorder) NotifyFailedLinks(ctx, chatID, links any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyFailedLinks", reflect.TypeOf((*MockBotNotifier)(nil).NotifyFailedLinks), ctx, chatID, links)
}

// MockLinkChecker is a mock of LinkChecker interface.
type MockLinkChecker struct {
	ctrl     *gomock.Controller
	recorder *MockLinkCheckerMockRecorder
	isgomock struct{}
}

// MockLinkCheckerMockRecorder is the mock recorder for MockLinkChecker.
type MockLinkCheckerMockRecorder struct {
	mock *MockLinkChecker
}

// NewMockLinkChecker creates a new mock instance.
func NewMockLinkChecker(ctrl *gomock.Controller) *MockLinkChecker {
	mock := &MockLinkChecker{ctrl: ctrl}
	mock.recorder = &MockLinkCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkChecker) EXPECT() *MockLinkCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockLinkChecker) Check(ctx context.Context, link domain.Link) (domain.LinkCheckOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, link)
	ret0, _ := ret[0].(domain.LinkCheckOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockLinkCheckerMockRecorder) Check(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockLinkChecker)(nil).Check), ctx, link)
}
