// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/bot/application (interfaces: Command,PlainMessageHandler,LinkTracker)
//
// Generated by this command:
//
//	mockgen -destination=internal/bot/application/mocks/mocks.go -package=mocks gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/bot/application Command,PlainMessageHandler,LinkTracker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/bot/application"
	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/bot/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
	isgomock struct{}
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// Description mocks base method.
func (m *MockCommand) Description() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Description")
	ret0, _ := ret[0].(string)
	return ret0
}

// Description indicates an expected call of Description.
func (mr *MockCommandMockRecorder) Description() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Description", reflect.TypeOf((*MockCommand)(nil).Description))
}

// Handle mocks base method.
func (m *MockCommand) Handle(action domain.Action) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", action)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockCommandMockRecorder) Handle(action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockCommand)(nil).Handle), action)
}

// Name mocks base method.
func (m *MockCommand) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCommandMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCommand)(nil).Name))
}

// MockPlainMessageHandler is a mock of PlainMessageHandler interface.
type MockPlainMessageHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPlainMessageHandlerMockRecorder
	isgomock struct{}
}

// MockPlainMessageHandlerMockRecorder is the mock recorder for MockPlainMessageHandler.
type MockPlainMessageHandlerMockRecorder struct {
	mock *MockPlainMessageHandler
}

// NewMockPlainMessageHandler creates a new mock instance.
func NewMockPlainMessageHandler(ctrl *gomock.Controller) *MockPlainMessageHandler {
	mock := &MockPlainMessageHandler{ctrl: ctrl}
	mock.recorder = &MockPlainMessageHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlainMessageHandler) EXPECT() *MockPlainMessageHandlerMockRecorder {
	return m.recorder
}

// HandlePlainMessage mocks base method.
func (m *MockPlainMessageHandler) HandlePlainMessage(action domain.Action) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandlePlainMessage", action)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandlePlainMessage indicates an expected call of HandlePlainMessage.
func (mr *MockPlainMessageHandlerMockRecorder) HandlePlainMessage(action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandlePlainMessage", reflect.TypeOf((*MockPlainMessageHandler)(nil).HandlePlainMessage), action)
}

// MockLinkTracker is a mock of LinkTracker interface.
type MockLinkTracker struct {
	ctrl     *gomock.Controller
	recorder *MockLinkTrackerMockRecorder
	isgomock struct{}
}

// MockLinkTrackerMockRecorder is the mock recorder for MockLinkTracker.
type MockLinkTrackerMockRecorder struct {
	mock *MockLinkTracker
}

// NewMockLinkTracker creates a new mock instance.
func NewMockLinkTracker(ctrl *gomock.Controller) *MockLinkTracker {
	mock := &MockLinkTracker{ctrl: ctrl}
	mock.recorder = &MockLinkTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkTracker) EXPECT() *MockLinkTrackerMockRecorder {
	return m.recorder
}

// AddLink mocks base method.
func (m *MockLinkTracker) AddLink(ctx context.Context, chatID int64, link string, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLink", ctx, chatID, link, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddLink indicates an expected call of AddLink.
func (mr *MockLinkTrackerMockRecorder) AddLink(ctx, chatID, link, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLink", reflect.TypeOf((*MockLinkTracker)(nil).AddLink), ctx, chatID, link, tags)
}

// ListLinks mocks base method.
func (m *MockLinkTracker) ListLinks(ctx context.Context, chatID int64, tagFilter string) ([]application.LinkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLinks", ctx, chatID, tagFilter)
	ret0, _ := ret[0].([]application.LinkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLinks indicates an expected call of ListLinks.
func (mr *MockLinkTrackerMockRecorder) ListLinks(ctx, chatID, tagFilter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLinks", reflect.TypeOf((*MockLinkTracker)(nil).ListLinks), ctx, chatID, tagFilter)
}

// RegisterChat mocks base method.
func (m *MockLinkTracker) RegisterChat(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterChat", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterChat indicates an expected call of RegisterChat.
func (mr *MockLinkTrackerMockRecorder) RegisterChat(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterChat", reflect.TypeOf((*MockLinkTracker)(nil).RegisterChat), ctx, chatID)
}

// RemoveLink mocks base method.
func (m *MockLinkTracker) RemoveLink(ctx context.Context, chatID int64, link string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveLink", ctx, chatID, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveLink indicates an expected call of RemoveLink.
func (mr *MockLinkTrackerMockRecorder) RemoveLink(ctx, chatID, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveLink", reflect.TypeOf((*MockLinkTracker)(nil).RemoveLink), ctx, chatID, link)
}
