access_type: "SQL" # SQL | ORM
postgres:
  user: "postgres"
  db: "linktracker"
  host: "localhost"
  port: "5432"
  ssl_mode: "disable"

logging:
  mode: "INFO" #variants ["INFO", "DEBUG"]

batch:
  size: 250 #50 - 500

scheduler:
  interval: "1m"
  workers: 4