// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChat = "chats"

// Chat mapped from table <chats>
type Chat struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TelegramID int64     `gorm:"column:telegram_id;not null" json:"telegram_id"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName Chat's table name
func (*Chat) TableName() string {
	return TableNameChat
}
