// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFilter = "filter"

// Filter mapped from table <filter>
type Filter struct {
	ID    int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Value string `gorm:"column:value;not null" json:"value"`
}

// TableName Filter's table name
func (*Filter) TableName() string {
	return TableNameFilter
}
