// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLinkFilter = "link_filter"

// LinkFilter mapped from table <link_filter>
type LinkFilter struct {
	SubscriptionID int64 `gorm:"column:subscription_id;primaryKey" json:"subscription_id"`
	FilterID       int64 `gorm:"column:filter_id;primaryKey" json:"filter_id"`
}

// TableName LinkFilter's table name
func (*LinkFilter) TableName() string {
	return TableNameLinkFilter
}
