// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLinkTag = "link_tag"

// LinkTag mapped from table <link_tag>
type LinkTag struct {
	SubscriptionID int64 `gorm:"column:subscription_id;primaryKey" json:"subscription_id"`
	TagID          int64 `gorm:"column:tag_id;primaryKey" json:"tag_id"`
}

// TableName LinkTag's table name
func (*LinkTag) TableName() string {
	return TableNameLinkTag
}
