// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLink = "links"

// Link mapped from table <links>
type Link struct {
	ID  int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	URL string `gorm:"column:url;not null" json:"url"`
}

// TableName Link's table name
func (*Link) TableName() string {
	return TableNameLink
}
