// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/agent/application (interfaces: UpdatePublisher,Summarizer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks . UpdatePublisher,Summarizer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/agent/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdatePublisher is a mock of UpdatePublisher interface.
type MockUpdatePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockUpdatePublisherMockRecorder
	isgomock struct{}
}

// MockUpdatePublisherMockRecorder is the mock recorder for MockUpdatePublisher.
type MockUpdatePublisherMockRecorder struct {
	mock *MockUpdatePublisher
}

// NewMockUpdatePublisher creates a new mock instance.
func NewMockUpdatePublisher(ctrl *gomock.Controller) *MockUpdatePublisher {
	mock := &MockUpdatePublisher{ctrl: ctrl}
	mock.recorder = &MockUpdatePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdatePublisher) EXPECT() *MockUpdatePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockUpdatePublisher) Publish(ctx context.Context, u domain.ProcessedUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockUpdatePublisherMockRecorder) Publish(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockUpdatePublisher)(nil).Publish), ctx, u)
}

// MockSummarizer is a mock of Summarizer interface.
type MockSummarizer struct {
	ctrl     *gomock.Controller
	recorder *MockSummarizerMockRecorder
	isgomock struct{}
}

// MockSummarizerMockRecorder is the mock recorder for MockSummarizer.
type MockSummarizerMockRecorder struct {
	mock *MockSummarizer
}

// NewMockSummarizer creates a new mock instance.
func NewMockSummarizer(ctrl *gomock.Controller) *MockSummarizer {
	mock := &MockSummarizer{ctrl: ctrl}
	mock.recorder = &MockSummarizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSummarizer) EXPECT() *MockSummarizerMockRecorder {
	return m.recorder
}

// Summarize mocks base method.
func (m *MockSummarizer) Summarize(ctx context.Context, text string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Summarize", ctx, text)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize.
func (mr *MockSummarizerMockRecorder) Summarize(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockSummarizer)(nil).Summarize), ctx, text)
}
